/*
 * MPL3115_Fields.hpp
 *
 *  Created on: Feb 22, 2025
 *      Author: Local user
 */

#ifndef MPL3115_FIELDS_HPP_
#define MPL3115_FIELDS_HPP_

#define MPL3115_FIELD_NOT_WRITEABLE \
  bool writeable() { return false; }
#define MPL3115_FIELD_LSB_INDEX(i) \
  const BIT_INDEX getLsbIndex() const { return i; }
#define MPL3115_FIELD_MSB_INDEX(i) \
  const BIT_INDEX getMsbIndex() const { return i; }
#define MPL3115_FIELD_REGISTER(r) \
  const MPL3115_REGISTER_t getReg() const { return r; }

enum class MPL3115_REGISTER_t {
  STATUS = 0x00,
  OUT_P_MSB,
  OUT_P_CSB,
  OUT_P_LSB,
  OUT_T_MSB,
  OUT_T_LSB,
  DR_STATUS,
  OUT_P_DELTA_MSB,
  OUT_P_DELTA_CSB,
  OUT_P_DELTA_LSB,
  OUT_T_DELTA_MSB,
  OUT_T_DELTA_LSB,
  WHO_AM_I,
  F_STATUS,
  F_DATA,
  F_SETUP,
  TIME_DLY,
  SYSMOD,
  INT_SOURCE,
  PT_DATA_CFG,
  BAR_IN_MSB,
  BAR_IN_LSB,
  P_TGT_MSB,
  P_TGT_LSB,
  T_TGT,
  P_WND_MSB,
  P_WND_LSB,
  T_WND,
  P_MIN_MSB,
  P_MIN_CSB,
  P_MIN_LSB,
  T_MIN_MSB,
  T_MIN_LSB,
  P_MAX_MSB,
  P_MAX_CSB,
  P_MAX_LSB,
  T_MAX_MSB,
  T_MAX_LSB,
  CTRL_REG1,
  CTRL_REG2,
  CTRL_REG3,
  CTRL_REG4,
  CTRL_REG5,
  OFF_P,
  OFF_T,
  OFF_H
};

typedef uint8_t BIT_INDEX;

class MPLSENSDriver;

struct MPL3115_FieldInfo {
  MPL3115_REGISTER_t reg;
  BIT_INDEX msbIndex;
  BIT_INDEX lsbIndex;
  const uint8_t GetNumBits() const;
  const bool writeable;
  bool operator==(const MPL3115_FieldInfo &other) const;
};

// Base class for a bit field within an MPL3115 register.
// Derived classes just overload the virtual functions to return their own
// constants.
class MPLSENSField {
 public:
  uint8_t GetNumBits();
  bool operator==(const MPLSENSField &other);
  const MPL3115_FieldInfo Info() const;
  virtual const BIT_INDEX getLsbIndex() const { return 0; }
  virtual const BIT_INDEX getMsbIndex() const { return 0; }
  virtual const MPL3115_REGISTER_t getReg() const {
    return MPL3115_REGISTER_t::WHO_AM_I;
  }
  operator MPL3115_FieldInfo() const { return Info(); }

  virtual bool writeable() const { return true; }
};

namespace MPL3115Fields {

class PTOW : public MPLSENSField {
 public:
  MPL3115_FIELD_LSB_INDEX(7);
  MPL3115_FIELD_MSB_INDEX(7);
  MPL3115_FIELD_REGISTER(MPL3115_REGISTER_t::DR_STATUS);
  MPL3115_FIELD_NOT_WRITEABLE;
};

class POW : public MPLSENSField {
 public:
  MPL3115_FIELD_LSB_INDEX(6);
  MPL3115_FIELD_MSB_INDEX(6);
  MPL3115_FIELD_REGISTER(MPL3115_REGISTER_t::DR_STATUS);
  MPL3115_FIELD_NOT_WRITEABLE;
};

class TOW : public MPLSENSField {
 public:
  MPL3115_FIELD_LSB_INDEX(5);
  MPL3115_FIELD_MSB_INDEX(5);
  MPL3115_FIELD_REGISTER(MPL3115_REGISTER_t::DR_STATUS);
  MPL3115_FIELD_NOT_WRITEABLE;
};

class PTDR : public MPLSENSField {
 public:
  MPL3115_FIELD_LSB_INDEX(3);
  MPL3115_FIELD_MSB_INDEX(3);
  MPL3115_FIELD_REGISTER(MPL3115_REGISTER_t::DR_STATUS);
  MPL3115_FIELD_NOT_WRITEABLE;
};

class PDR : public MPLSENSField {
 public:
  MPL3115_FIELD_LSB_INDEX(2);
  MPL3115_FIELD_MSB_INDEX(2);
  MPL3115_FIELD_REGISTER(MPL3115_REGISTER_t::DR_STATUS);
  MPL3115_FIELD_NOT_WRITEABLE;
};

class TDR : public MPLSENSField {
 public:
  MPL3115_FIELD_LSB_INDEX(1);
  MPL3115_FIELD_MSB_INDEX(1);
  MPL3115_FIELD_REGISTER(MPL3115_REGISTER_t::DR_STATUS);
  MPL3115_FIELD_NOT_WRITEABLE;
};

class OUT_P_MSB : public MPLSENSField {
 public:
  MPL3115_FIELD_LSB_INDEX(0);
  MPL3115_FIELD_MSB_INDEX(7);
  MPL3115_FIELD_REGISTER(MPL3115_REGISTER_t::OUT_P_MSB);
  MPL3115_FIELD_NOT_WRITEABLE;
};

class OUT_P_CSB : public MPLSENSField {
 public:
  MPL3115_FIELD_LSB_INDEX(0);
  MPL3115_FIELD_MSB_INDEX(7);
  MPL3115_FIELD_REGISTER(MPL3115_REGISTER_t::OUT_P_CSB);
  MPL3115_FIELD_NOT_WRITEABLE;
};

class OUT_P_LSB : public MPLSENSField {
 public:
  MPL3115_FIELD_LSB_INDEX(4);
  MPL3115_FIELD_MSB_INDEX(7);
  MPL3115_FIELD_REGISTER(MPL3115_REGISTER_t::OUT_P_LSB);
  MPL3115_FIELD_NOT_WRITEABLE;
};

class OUT_T_MSB : public MPLSENSField {
 public:
  MPL3115_FIELD_LSB_INDEX(0);
  MPL3115_FIELD_MSB_INDEX(7);
  MPL3115_FIELD_REGISTER(MPL3115_REGISTER_t::OUT_T_MSB);
  MPL3115_FIELD_NOT_WRITEABLE;
};

class OUT_T_LSB : public MPLSENSField {
 public:
  MPL3115_FIELD_LSB_INDEX(4);
  MPL3115_FIELD_MSB_INDEX(7);
  MPL3115_FIELD_REGISTER(MPL3115_REGISTER_t::OUT_T_LSB);
  MPL3115_FIELD_NOT_WRITEABLE;
};

// bingor

class OUT_P_DELTA_MSB : public MPLSENSField {
 public:
  MPL3115_FIELD_LSB_INDEX(0);
  MPL3115_FIELD_MSB_INDEX(7);
  MPL3115_FIELD_REGISTER(MPL3115_REGISTER_t::OUT_P_DELTA_MSB);
  MPL3115_FIELD_NOT_WRITEABLE;
};

class OUT_P_DELTA_CSB : public MPLSENSField {
 public:
  MPL3115_FIELD_LSB_INDEX(0);
  MPL3115_FIELD_MSB_INDEX(7);
  MPL3115_FIELD_REGISTER(MPL3115_REGISTER_t::OUT_P_DELTA_CSB);
  MPL3115_FIELD_NOT_WRITEABLE;
};

class OUT_P_DELTA_LSB : public MPLSENSField {
 public:
  MPL3115_FIELD_LSB_INDEX(4);
  MPL3115_FIELD_MSB_INDEX(7);
  MPL3115_FIELD_REGISTER(MPL3115_REGISTER_t::OUT_P_DELTA_LSB);
  MPL3115_FIELD_NOT_WRITEABLE;
};

class OUT_T_DELTA_MSB : public MPLSENSField {
 public:
  MPL3115_FIELD_LSB_INDEX(0);
  MPL3115_FIELD_MSB_INDEX(7);
  MPL3115_FIELD_REGISTER(MPL3115_REGISTER_t::OUT_T_DELTA_MSB);
  MPL3115_FIELD_NOT_WRITEABLE;
};

class OUT_T_DELTA_LSB : public MPLSENSField {
 public:
  MPL3115_FIELD_LSB_INDEX(4);
  MPL3115_FIELD_MSB_INDEX(7);
  MPL3115_FIELD_REGISTER(MPL3115_REGISTER_t::OUT_T_DELTA_LSB);
  MPL3115_FIELD_NOT_WRITEABLE;
};

class WHO_AM_I : public MPLSENSField {
 public:
  MPL3115_FIELD_LSB_INDEX(0);
  MPL3115_FIELD_MSB_INDEX(7);
  MPL3115_FIELD_REGISTER(MPL3115_REGISTER_t::WHO_AM_I);
  MPL3115_FIELD_NOT_WRITEABLE;
};

class F_OVF : public MPLSENSField {
 public:
  MPL3115_FIELD_LSB_INDEX(7);
  MPL3115_FIELD_MSB_INDEX(7);
  MPL3115_FIELD_REGISTER(MPL3115_REGISTER_t::F_STATUS);
  MPL3115_FIELD_NOT_WRITEABLE;
};

class F_WMRK_FLAG : public MPLSENSField {
 public:
  MPL3115_FIELD_LSB_INDEX(6);
  MPL3115_FIELD_MSB_INDEX(6);
  MPL3115_FIELD_REGISTER(MPL3115_REGISTER_t::F_STATUS);
  MPL3115_FIELD_NOT_WRITEABLE;
};

class F_CNT : public MPLSENSField {
 public:
  MPL3115_FIELD_LSB_INDEX(0);
  MPL3115_FIELD_MSB_INDEX(5);
  MPL3115_FIELD_REGISTER(MPL3115_REGISTER_t::F_STATUS);
  MPL3115_FIELD_NOT_WRITEABLE;
};

class F_DATA : public MPLSENSField {
 public:
  MPL3115_FIELD_LSB_INDEX(0);
  MPL3115_FIELD_MSB_INDEX(7);
  MPL3115_FIELD_REGISTER(MPL3115_REGISTER_t::F_DATA);
  MPL3115_FIELD_NOT_WRITEABLE;
};

class F_MODE : public MPLSENSField {
 public:
  MPL3115_FIELD_LSB_INDEX(6);
  MPL3115_FIELD_MSB_INDEX(7);
  MPL3115_FIELD_REGISTER(MPL3115_REGISTER_t::F_SETUP);
  MPL3115_FIELD_NOT_WRITEABLE;
};

class F_WMRK : public MPLSENSField {
 public:
  MPL3115_FIELD_LSB_INDEX(0);
  MPL3115_FIELD_MSB_INDEX(5);
  MPL3115_FIELD_REGISTER(MPL3115_REGISTER_t::F_SETUP);
  MPL3115_FIELD_NOT_WRITEABLE;
};

class TIME_DLY : public MPLSENSField {
 public:
  MPL3115_FIELD_LSB_INDEX(0);
  MPL3115_FIELD_MSB_INDEX(7);
  MPL3115_FIELD_REGISTER(MPL3115_REGISTER_t::TIME_DLY);
  MPL3115_FIELD_NOT_WRITEABLE;
};

class SYSMOD : public MPLSENSField {
 public:
  MPL3115_FIELD_LSB_INDEX(0);
  MPL3115_FIELD_MSB_INDEX(0);
  MPL3115_FIELD_REGISTER(MPL3115_REGISTER_t::SYSMOD);
  MPL3115_FIELD_NOT_WRITEABLE;
};

class SRC_DRDY : public MPLSENSField {
 public:
  MPL3115_FIELD_LSB_INDEX(7);
  MPL3115_FIELD_MSB_INDEX(7);
  MPL3115_FIELD_REGISTER(MPL3115_REGISTER_t::INT_SOURCE);
  MPL3115_FIELD_NOT_WRITEABLE;
};

class SRC_FIFO : public MPLSENSField {
 public:
  MPL3115_FIELD_LSB_INDEX(6);
  MPL3115_FIELD_MSB_INDEX(6);
  MPL3115_FIELD_REGISTER(MPL3115_REGISTER_t::INT_SOURCE);
  MPL3115_FIELD_NOT_WRITEABLE;
};

class SRC_PW : public MPLSENSField {
 public:
  MPL3115_FIELD_LSB_INDEX(5);
  MPL3115_FIELD_MSB_INDEX(5);
  MPL3115_FIELD_REGISTER(MPL3115_REGISTER_t::INT_SOURCE);
  MPL3115_FIELD_NOT_WRITEABLE;
};

class SRC_TW : public MPLSENSField {
 public:
  MPL3115_FIELD_LSB_INDEX(4);
  MPL3115_FIELD_MSB_INDEX(4);
  MPL3115_FIELD_REGISTER(MPL3115_REGISTER_t::INT_SOURCE);
  MPL3115_FIELD_NOT_WRITEABLE;
};

class SRC_PTH : public MPLSENSField {
 public:
  MPL3115_FIELD_LSB_INDEX(3);
  MPL3115_FIELD_MSB_INDEX(3);
  MPL3115_FIELD_REGISTER(MPL3115_REGISTER_t::INT_SOURCE);
  MPL3115_FIELD_NOT_WRITEABLE;
};

class SRC_TTH : public MPLSENSField {
 public:
  MPL3115_FIELD_LSB_INDEX(2);
  MPL3115_FIELD_MSB_INDEX(2);
  MPL3115_FIELD_REGISTER(MPL3115_REGISTER_t::INT_SOURCE);
  MPL3115_FIELD_NOT_WRITEABLE;
};

class SRC_PCHG : public MPLSENSField {
 public:
  MPL3115_FIELD_LSB_INDEX(1);
  MPL3115_FIELD_MSB_INDEX(1);
  MPL3115_FIELD_REGISTER(MPL3115_REGISTER_t::INT_SOURCE);
  MPL3115_FIELD_NOT_WRITEABLE;
};

class SRC_TCHG : public MPLSENSField {
 public:
  MPL3115_FIELD_LSB_INDEX(0);
  MPL3115_FIELD_MSB_INDEX(0);
  MPL3115_FIELD_REGISTER(MPL3115_REGISTER_t::INT_SOURCE);
  MPL3115_FIELD_NOT_WRITEABLE;
};

class DREM : public MPLSENSField {
 public:
  MPL3115_FIELD_LSB_INDEX(2);
  MPL3115_FIELD_MSB_INDEX(2);
  MPL3115_FIELD_REGISTER(MPL3115_REGISTER_t::PT_DATA_CFG);
};

class PDEFE : public MPLSENSField {
 public:
  MPL3115_FIELD_LSB_INDEX(1);
  MPL3115_FIELD_MSB_INDEX(1);
  MPL3115_FIELD_REGISTER(MPL3115_REGISTER_t::PT_DATA_CFG);
};

class TDEFE : public MPLSENSField {
 public:
  MPL3115_FIELD_LSB_INDEX(0);
  MPL3115_FIELD_MSB_INDEX(0);
  MPL3115_FIELD_REGISTER(MPL3115_REGISTER_t::PT_DATA_CFG);
};

class BAR_IN_MSB : public MPLSENSField {
 public:
  MPL3115_FIELD_LSB_INDEX(0);
  MPL3115_FIELD_MSB_INDEX(7);
  MPL3115_FIELD_REGISTER(MPL3115_REGISTER_t::BAR_IN_MSB);
};

class BAR_IN_LSB : public MPLSENSField {
 public:
  MPL3115_FIELD_LSB_INDEX(0);
  MPL3115_FIELD_MSB_INDEX(7);
  MPL3115_FIELD_REGISTER(MPL3115_REGISTER_t::BAR_IN_LSB);
};

class P_TGT_MSB : public MPLSENSField {
 public:
  MPL3115_FIELD_LSB_INDEX(0);
  MPL3115_FIELD_MSB_INDEX(7);
  MPL3115_FIELD_REGISTER(MPL3115_REGISTER_t::P_TGT_MSB);
};

class P_TGT_LSB : public MPLSENSField {
 public:
  MPL3115_FIELD_LSB_INDEX(0);
  MPL3115_FIELD_MSB_INDEX(7);
  MPL3115_FIELD_REGISTER(MPL3115_REGISTER_t::P_TGT_LSB);
};

class T_TGT : public MPLSENSField {
 public:
  MPL3115_FIELD_LSB_INDEX(0);
  MPL3115_FIELD_MSB_INDEX(7);
  MPL3115_FIELD_REGISTER(MPL3115_REGISTER_t::T_TGT);
};

class P_WND_LSB : public MPLSENSField {
 public:
  MPL3115_FIELD_LSB_INDEX(0);
  MPL3115_FIELD_MSB_INDEX(7);
  MPL3115_FIELD_REGISTER(MPL3115_REGISTER_t::P_WND_LSB);
};

class P_WND_MSB : public MPLSENSField {
 public:
  MPL3115_FIELD_LSB_INDEX(0);
  MPL3115_FIELD_MSB_INDEX(7);
  MPL3115_FIELD_REGISTER(MPL3115_REGISTER_t::P_WND_MSB);
};

class T_WIN : public MPLSENSField {
 public:
  MPL3115_FIELD_LSB_INDEX(0);
  MPL3115_FIELD_MSB_INDEX(7);
  MPL3115_FIELD_REGISTER(MPL3115_REGISTER_t::T_WND);
};

class P_MIN_MSB : public MPLSENSField {
 public:
  MPL3115_FIELD_LSB_INDEX(0);
  MPL3115_FIELD_MSB_INDEX(7);
  MPL3115_FIELD_REGISTER(MPL3115_REGISTER_t::P_MIN_MSB);
};

class P_MIN_CSB : public MPLSENSField {
 public:
  MPL3115_FIELD_LSB_INDEX(0);
  MPL3115_FIELD_MSB_INDEX(7);
  MPL3115_FIELD_REGISTER(MPL3115_REGISTER_t::P_MIN_CSB);
};

class P_MIN_LSB : public MPLSENSField {
 public:
  MPL3115_FIELD_LSB_INDEX(4);
  MPL3115_FIELD_MSB_INDEX(7);
  MPL3115_FIELD_REGISTER(MPL3115_REGISTER_t::P_MIN_LSB);
};

class P_MAX_MSB : public MPLSENSField {
 public:
  MPL3115_FIELD_LSB_INDEX(0);
  MPL3115_FIELD_MSB_INDEX(7);
  MPL3115_FIELD_REGISTER(MPL3115_REGISTER_t::P_MAX_MSB);
};

class P_MAX_CSB : public MPLSENSField {
 public:
  MPL3115_FIELD_LSB_INDEX(0);
  MPL3115_FIELD_MSB_INDEX(7);
  MPL3115_FIELD_REGISTER(MPL3115_REGISTER_t::P_MAX_CSB);
};

class P_MAX_LSB : public MPLSENSField {
 public:
  MPL3115_FIELD_LSB_INDEX(4);
  MPL3115_FIELD_MSB_INDEX(7);
  MPL3115_FIELD_REGISTER(MPL3115_REGISTER_t::P_MAX_LSB);
};

class T_MIN_MSB : public MPLSENSField {
 public:
  MPL3115_FIELD_LSB_INDEX(0);
  MPL3115_FIELD_MSB_INDEX(7);
  MPL3115_FIELD_REGISTER(MPL3115_REGISTER_t::T_MIN_MSB);
};

class T_MIN_LSB : public MPLSENSField {
 public:
  MPL3115_FIELD_LSB_INDEX(4);
  MPL3115_FIELD_MSB_INDEX(7);
  MPL3115_FIELD_REGISTER(MPL3115_REGISTER_t::T_MIN_LSB);
};

class T_MAX_MSB : public MPLSENSField {
 public:
  MPL3115_FIELD_LSB_INDEX(0);
  MPL3115_FIELD_MSB_INDEX(7);
  MPL3115_FIELD_REGISTER(MPL3115_REGISTER_t::T_MAX_MSB);
};

class T_MAX_LSB : public MPLSENSField {
 public:
  MPL3115_FIELD_LSB_INDEX(4);
  MPL3115_FIELD_MSB_INDEX(7);
  MPL3115_FIELD_REGISTER(MPL3115_REGISTER_t::T_MAX_LSB);
};

class ALT : public MPLSENSField {
 public:
  MPL3115_FIELD_LSB_INDEX(7);
  MPL3115_FIELD_MSB_INDEX(7);
  MPL3115_FIELD_REGISTER(MPL3115_REGISTER_t::CTRL_REG1);
};

class OS : public MPLSENSField {
 public:
  MPL3115_FIELD_LSB_INDEX(3);
  MPL3115_FIELD_MSB_INDEX(5);
  MPL3115_FIELD_REGISTER(MPL3115_REGISTER_t::CTRL_REG1);
};

class RST : public MPLSENSField {
 public:
  MPL3115_FIELD_LSB_INDEX(2);
  MPL3115_FIELD_MSB_INDEX(2);
  MPL3115_FIELD_REGISTER(MPL3115_REGISTER_t::CTRL_REG1);
};

class OST : public MPLSENSField {
 public:
  MPL3115_FIELD_LSB_INDEX(1);
  MPL3115_FIELD_MSB_INDEX(1);
  MPL3115_FIELD_REGISTER(MPL3115_REGISTER_t::CTRL_REG1);
};

class SBYB : public MPLSENSField {
 public:
  MPL3115_FIELD_LSB_INDEX(0);
  MPL3115_FIELD_MSB_INDEX(0);
  MPL3115_FIELD_REGISTER(MPL3115_REGISTER_t::CTRL_REG1);
};

class LOAD_OUTPUT : public MPLSENSField {
 public:
  MPL3115_FIELD_LSB_INDEX(5);
  MPL3115_FIELD_MSB_INDEX(5);
  MPL3115_FIELD_REGISTER(MPL3115_REGISTER_t::CTRL_REG2);
};

class ALARM_SEL : public MPLSENSField {
 public:
  MPL3115_FIELD_LSB_INDEX(4);
  MPL3115_FIELD_MSB_INDEX(4);
  MPL3115_FIELD_REGISTER(MPL3115_REGISTER_t::CTRL_REG2);
};

class ST : public MPLSENSField {
 public:
  MPL3115_FIELD_LSB_INDEX(0);
  MPL3115_FIELD_MSB_INDEX(3);
  MPL3115_FIELD_REGISTER(MPL3115_REGISTER_t::CTRL_REG2);
};

class IPOL1 : public MPLSENSField {
 public:
  MPL3115_FIELD_LSB_INDEX(5);
  MPL3115_FIELD_MSB_INDEX(5);
  MPL3115_FIELD_REGISTER(MPL3115_REGISTER_t::CTRL_REG3);
};

class PP_OD1 : public MPLSENSField {
 public:
  MPL3115_FIELD_LSB_INDEX(4);
  MPL3115_FIELD_MSB_INDEX(4);
  MPL3115_FIELD_REGISTER(MPL3115_REGISTER_t::CTRL_REG3);
};

class IPOL2 : public MPLSENSField {
 public:
  MPL3115_FIELD_LSB_INDEX(1);
  MPL3115_FIELD_MSB_INDEX(1);
  MPL3115_FIELD_REGISTER(MPL3115_REGISTER_t::CTRL_REG3);
};

class PP_OD2 : public MPLSENSField {
 public:
  MPL3115_FIELD_LSB_INDEX(0);
  MPL3115_FIELD_MSB_INDEX(0);
  MPL3115_FIELD_REGISTER(MPL3115_REGISTER_t::CTRL_REG3);
};

class OFF_P : public MPLSENSField {
 public:
  MPL3115_FIELD_LSB_INDEX(0);
  MPL3115_FIELD_MSB_INDEX(7);
  MPL3115_FIELD_REGISTER(MPL3115_REGISTER_t::OFF_P);
};

class OFF_T : public MPLSENSField {
 public:
  MPL3115_FIELD_LSB_INDEX(0);
  MPL3115_FIELD_MSB_INDEX(7);
  MPL3115_FIELD_REGISTER(MPL3115_REGISTER_t::OFF_T);
};

class OFF_H : public MPLSENSField {
 public:
  MPL3115_FIELD_LSB_INDEX(0);
  MPL3115_FIELD_MSB_INDEX(7);
  MPL3115_FIELD_REGISTER(MPL3115_REGISTER_t::OFF_H);
};
}  // namespace MPL3115Fields

inline const uint8_t MPL3115_FieldInfo::GetNumBits() const {
  return msbIndex - lsbIndex + 1;
}

inline bool MPL3115_FieldInfo::operator==(
    const MPL3115_FieldInfo &other) const {
  if (other.lsbIndex == lsbIndex && other.msbIndex == msbIndex &&
      other.reg == reg) {
    return true;
  }
  return false;
}

#endif /* MPL3115_FIELDS_HPP_ */
