/*
 * main_nau7802_test.cpp
 *
 * Example usage file for the refactored NAU7802 driver.
 * This example initializes the sensor with 1x gain
 * and continuously reads the raw ADC value.
 */

/* Includes ------------------------------------------------------------------*/
#include "main.h"
#include "I2C_Wrapper.hpp"
#include "NAU7802.hpp"
#include <stdio.h> // For printf debugging

/* Private variables ---------------------------------------------------------*/
// Assume hi2c1 is generated by STM32CubeIDE and initialized in main()
extern I2C_HandleTypeDef hi2c1; // Declaration of hi2c1

/* Function Prototypes -------------------------------------------------------*/
// These are assumed to be in main.h or defined in main.c
void SystemClock_Config(void);
static void MX_GPIO_Init(void);
static void MX_I2C1_Init(void); 
extern void Error_Handler(void); // Assuming this is defined in main.c

/**
  * @brief  The application entry point.
  */
int main(void)
{
  /* MCU Configuration--------------------------------------------------------*/
  HAL_Init();
  SystemClock_Config();
  MX_GPIO_Init();
  MX_I2C1_Init(); // This initializes hi2c1

  /* --- SETUP STAGE --- */
  // 1. create wrapper and config structs
  I2C_Wrapper i2c_bus_1(&hi2c1);
  NAU7802_PARAMS adc_config;
  NAU7802_OUT adc_data;
  // 3. Configure parameters
  adc_config.initialGain = NAU7802_GAIN_1X; // Set to 1x gain as requested
  
  // 4. Create the driver object
  NAU7802 adc(adc_config, i2c_bus_1);

  // 5. Check if initialization was successful
  if (!adc.get_isInitialized()) 
  {
    // ADC not found or failed to configure
    // printf("NAU7802 Initialization Failed!\r\n");
    Error_Handler();
  }
  
  // printf("NAU7802 Initialized. Gain set to 1x.\r\n");

  /* --- MAIN LOOP --- */
  while (1)
  {
    // 7. Check if data is ready (Step 6 is creating the output struct, done globally)
    if (adc.isReady()) 
    {
      // 8. Read data
      if (adc.readSensor(&adc_data) == HAL_OK)
      {
        // You UART debug print here:
        // printf("Raw ADC Value (Gain 1x): %ld\r\n", adc_data.raw_reading);
      }
    }
    HAL_Delay(100); // Wait 100ms before checking again
  }
}